version: "3.9"

services:
  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx
  #   restart: unless-stopped
  #   tty: true
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./:/var/www/html
  #     - ./nginx/conf.d/:/etc/nginx/conf.d/
  #     - ./nginx/ssl/:/etc/nginx/ssl/

  example_database:
    image: mysql:8.0
    container_name: trainning_database
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysqldata:/var/lib/mysql

  #api backend
  example_backend_api:
    depends_on:
      - example_database
    build:
      context: .
      dockerfile: DockerFile
    container_name: trainning_backend
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    ports:
      - 8000:8000
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./docker/supervisor.conf:/etc/supervisor/supervisord.conf

volumes:
    mysqldata:
